### PR TITLE
Parser upgrade

### PR DESCRIPTION
**Pull request by ackledotdev**

### CODE REVIEW

**Comment by akpi816218** [comment]
@flowerlovingatheist there's some issues that I fixed previously that come up again in your version. I'll try to manually merge my changes by hand :)
see snippet from merged `pronouns.json`:
```jsonc
// ...
{
	"strascii": "Spelling (far from spealer)",
	"type": "pronoun",
	"eng_trans": "English Equivalent",
	"def": "Implication / Definition / Used as",
	"strascii_obscure": ""
},
// ...
```

**Comment by akpi816218** [comment]
@flowerlovingatheist there's some issues that I fixed previously that come up again in your version. I'll try to manually merge my changes by hand :)
see snippet from merged `pronouns.json`:
```jsonc
// ...
{
	"strascii": "Spelling (far from spealer)",
	"type": "pronoun",
	"eng_trans": "English Equivalent",
	"def": "Implication / Definition / Used as",
	"strascii_obscure": ""
},
// ...
```

**Comment by akpi816218** [comment]
also this is **NOT READY TO MERGE**, the JSON files do not fit the proper schema.
Currently trying to copy over & properly integrate my section-respective algorithm.

**Comment by akpi816218** [comment]
sorry I'm talking on GitHub, I can't access Discord on my computer at school
but @flowerlovingatheist could you have future commit messages detail exactly what they change? ty

**Comment by akpi816218** [comment]
Looks good to merge, need review by @flowerlovingatheist 
Also, Discord bot needs to be updated to follow new spec prior to merge

**Review by 684pika — APPROVED** [review]
Looks all good to me!

**Pull request merged**
