### PR TITLE
Update Phonetics.md

### PR DESCRIPTION
**Pull request by flowerlovingatheist**
(actually) improved formatting

### CODE REVIEW

**Comment by miraneko** [comment]
we typically don't format like that

**Comment by flowerlovingatheist** [comment]
wdym? it's an itemised list, and even though we haven't used them a lot, i see no reason why it shouldn't be used in this situation it is and looks objectively better. thery're used in the [Formatting.md](../blob/main/Formatting.md) md page btw

**Comment by flowerlovingatheist** [comment]
wdym? it's just an itemised list, i see no reason why we shouldn't use it, it isn't weird formatting or anything and it looks objectively better. we use itemised lists in [Formatting.md](../blob/main/Formatting.md) btw and i see no reason for that to change

**Comment by flowerlovingatheist** [comment]
yes, but i see absolutely no reason for why it shouldn't be able to be used

**Pull request merged**
